namespace Project.App;
public enum SfxEnums
{
    ArrowHit,
    BossIntro,
    BowAttack,
    ChestOpen,
    Equip,
    FireballHit,
    GameOver,
    GameStart,
    Hit,
    MenuDown,
    MenuMove,
    MenuSelect,
    MenuUp,
    OrcAttack,
    OrcDeath,
    OrcHit,
    Pickup,
    PlayerDeath,
    PlayerHit,
    PlayerStep,
    Potion,
    ScepterAttack,
    SkeletonAttack,
    SkeletonDeath,
    SkeletonHit,
    SwordAttack,
    WandAttack,

}